//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stories
    {
        public int PKStoryId { get; set; }
        public Nullable<int> FKCategoryId { get; set; }
        public Nullable<int> FKWriterId { get; set; }
        public string Body { get; set; }
        public bool IsActive { get; set; }
    }
}
