//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Writer
    {
        public int PKWriterId { get; set; }
        public string WriterName { get; set; }
        public bool Daily { get; set; }
        public bool IsActive { get; set; }
    }
}
